/**
 * Built-in node definitions for Onion Flow.
 * These are compiled into the app — no external file system needed.
 */
import { NODE_CATEGORY_COLORS, type NodeTypeDefinition } from './types'

export const BUILTIN_NODES: NodeTypeDefinition[] = [
  // ── Context Nodes ──
  {
    type: 'personality',
    label: 'Personality',
    labelKo: '성격',
    category: 'context',
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: '성격' },
  },
  {
    type: 'appearance',
    label: 'Appearance',
    labelKo: '외모',
    category: 'context',
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: '외모' },
  },
  {
    type: 'memory',
    label: 'Memory',
    labelKo: '기억',
    category: 'context',
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: '기억' },
  },
  {
    type: 'character',
    label: 'Character',
    labelKo: '캐릭터',
    category: 'context',
    color: NODE_CATEGORY_COLORS.context,
    inputs: [
      { id: 'personality', label: '성격', type: 'target', position: 'left' },
      { id: 'appearance', label: '외모', type: 'target', position: 'left' },
      { id: 'memory', label: '기억', type: 'target', position: 'left' },
    ],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, position: 'neutral', label: 'Character' },
  },
  {
    type: 'event',
    label: 'Event/Environment',
    labelKo: '사건/환경',
    category: 'context',
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: 'Event' },
  },
  {
    type: 'wiki',
    label: 'Wiki Data',
    labelKo: '위키 데이터',
    category: 'context',
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: 'Wiki' },
  },

  // ── Direction Nodes ──
  {
    type: 'pov',
    label: 'POV Control',
    labelKo: '시점 제어',
    category: 'direction',
    color: NODE_CATEGORY_COLORS.direction,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { povType: 'third_limited', characterId: null, label: 'POV' },
  },
  {
    type: 'pacing',
    label: 'Pacing',
    labelKo: '텐션/호흡',
    category: 'direction',
    color: NODE_CATEGORY_COLORS.direction,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { tension: 5, speed: 'normal', label: 'Pacing' },
  },
  {
    type: 'style_transfer',
    label: 'Style Transfer',
    labelKo: '문체 학습',
    category: 'direction',
    color: NODE_CATEGORY_COLORS.direction,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { sampleText: '', authorName: '', label: 'Style' },
  },

  // ── Processing Nodes ──
  {
    type: 'storyteller',
    label: 'AI Storyteller',
    labelKo: 'AI 스토리텔러',
    category: 'processing',
    color: NODE_CATEGORY_COLORS.processing,
    inputs: [
      { id: 'context', label: 'Context', type: 'target', position: 'left' },
      { id: 'direction', label: 'Direction', type: 'target', position: 'left' },
    ],
    outputs: [{ id: 'out', label: 'Text', type: 'source', position: 'right' }],
    defaultData: { prompt: '', label: 'Storyteller', provider: null },
  },
  {
    type: 'summarizer',
    label: 'Summarizer',
    labelKo: '스토리 축약',
    category: 'processing',
    color: NODE_CATEGORY_COLORS.processing,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Summary', type: 'source', position: 'right' }],
    defaultData: { maxTokens: 500, label: 'Summarizer' },
  },

  // ── Special Nodes ──
  {
    type: 'what_if',
    label: 'What-If Branch',
    labelKo: '평행우주 분기',
    category: 'special',
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'in', label: 'Scene', type: 'target', position: 'left' }],
    outputs: [
      { id: 'branch_a', label: 'Branch A', type: 'source', position: 'right' },
      { id: 'branch_b', label: 'Branch B', type: 'source', position: 'right' },
    ],
    defaultData: { label: 'What-If' },
  },
  {
    type: 'show_dont_tell',
    label: "Show Don't Tell",
    labelKo: '묘사 증폭',
    category: 'special',
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { label: 'Show' },
  },
  {
    type: 'tikitaka',
    label: 'Tikitaka Dialogue',
    labelKo: '티키타카 대화',
    category: 'special',
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'characters', label: 'Characters', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Dialogue', type: 'source', position: 'right' }],
    defaultData: { turns: 10, label: 'Tikitaka' },
  },
  {
    type: 'cliffhanger',
    label: 'Cliffhanger',
    labelKo: '절단신공',
    category: 'special',
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'in', label: 'Scene', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Endings', type: 'source', position: 'right' }],
    defaultData: { count: 3, label: 'Cliffhanger' },
  },
  {
    type: 'virtual_reader',
    label: 'Virtual Reader',
    labelKo: '가상 독자',
    category: 'special',
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'in', label: 'Manuscript', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Feedback', type: 'source', position: 'right' }],
    defaultData: { personas: ['사이다패스', '설정덕후', '감성독자'], label: 'Reader' },
  },

  // ── Detector Nodes ──
  {
    type: 'emotion_tracker',
    label: 'Emotion Tracker',
    labelKo: '감정 트래커',
    category: 'detector',
    color: NODE_CATEGORY_COLORS.detector,
    inputs: [{ id: 'in', label: 'Text', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Emotions', type: 'source', position: 'right' }],
    defaultData: { label: 'Emotion' },
  },
  {
    type: 'foreshadow_detector',
    label: 'Foreshadow Detector',
    labelKo: '복선 디텍터',
    category: 'detector',
    color: NODE_CATEGORY_COLORS.detector,
    inputs: [{ id: 'in', label: 'Text', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Foreshadows', type: 'source', position: 'right' }],
    defaultData: { label: 'Foreshadow' },
  },
  {
    type: 'conflict_defense',
    label: 'Conflict Defense',
    labelKo: '설정 충돌 방어',
    category: 'detector',
    color: NODE_CATEGORY_COLORS.detector,
    inputs: [{ id: 'in', label: 'Text', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Warnings', type: 'source', position: 'right' }],
    defaultData: { label: 'Conflict' },
  },

  // ── Output Nodes ──
  {
    type: 'save_story',
    label: 'Save Story',
    labelKo: '스토리 저장',
    category: 'output',
    color: NODE_CATEGORY_COLORS.output,
    inputs: [{ id: 'story', label: 'Story', type: 'target', position: 'left' }],
    outputs: [],
    defaultData: { filename: 'story.md', label: 'Save Story' },
  },

  // ── Structure Nodes ──
  {
    type: 'group',
    label: 'Group',
    labelKo: '그룹',
    category: 'structure',
    color: NODE_CATEGORY_COLORS.structure,
    inputs: [],
    outputs: [],
    defaultData: { label: 'Group' },
  },

  // ── Plot Nodes: 주제적/서사적 플롯 ──
  {
    type: 'plot_overcome',
    label: 'Overcoming the Monster',
    labelKo: '극복 서사',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '주인공이 거대한 악/위협을 극복하는 서사', label: '극복 서사' },
  },
  {
    type: 'plot_hero_journey',
    label: "Hero's Journey",
    labelKo: '영웅의 여정',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '일상→모험→시련→귀환의 영웅 서사 구조', label: '영웅의 여정' },
  },
  {
    type: 'plot_rags_to_riches',
    label: 'Rags to Riches',
    labelKo: '왕에서 거지로',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '신분이나 지위의 극적인 상승 또는 하락 서사', label: '왕에서 거지로' },
  },
  {
    type: 'plot_tragedy',
    label: 'Tragedy',
    labelKo: '비극',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '주인공의 결함이나 운명으로 인한 몰락 서사', label: '비극' },
  },
  {
    type: 'plot_comedy',
    label: 'Comedy',
    labelKo: '코미디',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '혼란과 오해를 거쳐 행복한 결말에 이르는 서사', label: '코미디' },
  },
  {
    type: 'plot_rebirth',
    label: 'Rebirth',
    labelKo: '재탄생',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '주인공이 변화/각성을 통해 새로운 삶을 얻는 서사', label: '재탄생' },
  },
  {
    type: 'plot_voyage_return',
    label: 'Voyage and Return',
    labelKo: '탐험과 귀환',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '미지의 세계로 떠나 경험 후 돌아오는 서사', label: '탐험과 귀환' },
  },
  {
    type: 'plot_forbidden_love',
    label: 'Forbidden Love',
    labelKo: '금지된 사랑',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '사회적/도덕적 금기를 넘는 사랑의 서사', label: '금지된 사랑' },
  },
  {
    type: 'plot_revenge',
    label: 'Revenge',
    labelKo: '복수 서사',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '부당한 피해에 대한 복수와 그 대가를 다루는 서사', label: '복수 서사' },
  },
  {
    type: 'plot_mystery',
    label: 'Mystery/Detective',
    labelKo: '미스터리/탐정 서사',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'thematic', description: '수수께끼를 풀어나가며 진실에 다가가는 서사', label: '미스터리/탐정 서사' },
  },

  // ── Plot Nodes: 구조적 플롯 ──
  {
    type: 'plot_linear',
    label: 'Linear Plot',
    labelKo: '선형 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'structural', description: '시간 순서대로 전개되는 직선적 구조', label: '선형 플롯' },
  },
  {
    type: 'plot_nonlinear',
    label: 'Nonlinear Plot',
    labelKo: '비선형 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'structural', description: '시간 순서를 벗어나 교차/역행하는 구조 (플래시백, 플래시포워드)', label: '비선형 플롯' },
  },
  {
    type: 'plot_circular',
    label: 'Circular Plot',
    labelKo: '원형/순환 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'structural', description: '결말이 시작과 연결되어 순환하는 구조', label: '원형/순환 플롯' },
  },
  {
    type: 'plot_episodic',
    label: 'Episodic Plot',
    labelKo: '에피소딕 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'structural', description: '독립적인 에피소드가 느슨하게 연결되는 구조', label: '에피소딕 플롯' },
  },
  {
    type: 'plot_three_act',
    label: 'Three-Act Structure',
    labelKo: '3막 구조',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'structural', description: '설정(1막)→대립(2막)→해결(3막)의 고전적 구조', label: '3막 구조' },
  },
  {
    type: 'plot_five_act',
    label: 'Five-Act Structure',
    labelKo: '5막 구조',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'structural', description: '발단→상승→절정→하강→대단원의 5단계 구조', label: '5막 구조' },
  },
  {
    type: 'plot_freytag',
    label: "Freytag's Pyramid",
    labelKo: '프레이태그의 피라미드',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'structural', description: '도입→상승→클라이맥스→하강→결말의 피라미드형 구조', label: '프레이태그의 피라미드' },
  },

  // ── Plot Nodes: 현대적/장르별 플롯 ──
  {
    type: 'plot_dystopia',
    label: 'Dystopian Plot',
    labelKo: '디스토피아적 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'modern', description: '억압적 사회에 대한 저항과 자유를 향한 서사', label: '디스토피아적 플롯' },
  },
  {
    type: 'plot_thriller',
    label: 'Thriller Plot',
    labelKo: '스릴러 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'modern', description: '긴장감과 서스펜스 중심의 위기 해결 서사', label: '스릴러 플롯' },
  },
  {
    type: 'plot_romance',
    label: 'Romance Plot',
    labelKo: '로맨스 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'modern', description: '만남→갈등→화해→결합의 사랑 서사', label: '로맨스 플롯' },
  },
  {
    type: 'plot_horror',
    label: 'Horror Plot',
    labelKo: '호러 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'modern', description: '공포와 불안을 조성하며 생존/탈출을 다루는 서사', label: '호러 플롯' },
  },
  {
    type: 'plot_experimental',
    label: 'Experimental Plot',
    labelKo: '초현실적/실험적 플롯',
    category: 'plot',
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [],
    outputs: [{ id: 'out', label: 'Plot', type: 'source', position: 'right' }],
    defaultData: { subCategory: 'modern', description: '전통적 서사 규칙을 벗어난 실험적/초현실적 구조', label: '초현실적/실험적 플롯' },
  },
]
