/**
 * Built-in node definitions for Onion Flow.
 * These are compiled into the app — no external file system needed.
 *
 * Each node must include a `tags` array for the flat tag-based node picker.
 * The `category` field is still used for color grouping and execution routing.
 */
import { NODE_CATEGORY_COLORS, type NodeTypeDefinition } from './types'

export const BUILTIN_NODES: NodeTypeDefinition[] = [
  // ── Context Nodes ──
  {
    type: 'memory',
    label: 'Memory',
    labelKo: '기억',
    category: 'context',
    tags: ['context', 'character', 'wiki'],
    color: NODE_CATEGORY_COLORS.context,
    inputs: [{ id: 'plot_in', label: '플롯', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: '기억' },
  },
  {
    type: 'motivation',
    label: 'Motivation',
    labelKo: '동기',
    category: 'context',
    tags: ['context', 'character', 'wiki'],
    color: NODE_CATEGORY_COLORS.context,
    inputs: [{ id: 'plot_in', label: '플롯', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: '동기' },
  },
  {
    type: 'character',
    label: 'Character',
    labelKo: '캐릭터',
    category: 'context',
    tags: ['context', 'character', 'wiki'],
    color: NODE_CATEGORY_COLORS.context,
    inputs: [
      { id: 'motivation_in', label: '동기', type: 'target', position: 'left' },
      { id: 'memory_in', label: '기억', type: 'target', position: 'left' },
    ],
    outputs: [
      { id: 'out', label: 'Data', type: 'source', position: 'right' },
      { id: 'timeline', label: 'Timeline', type: 'source', position: 'right' },
      { id: 'state', label: 'State', type: 'source', position: 'right' },
    ],
    defaultData: {
      wikiEntryId: null,
      label: 'Character',
    },
  },
  {
    type: 'event',
    label: 'Event/Environment',
    labelKo: '사건/환경',
    category: 'context',
    tags: ['context', 'wiki'],
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: 'Event' },
  },
  {
    type: 'wiki',
    label: 'Wiki Data',
    labelKo: '위키 데이터',
    category: 'context',
    tags: ['context', 'wiki', 'data'],
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { wikiEntryId: null, label: 'Wiki' },
  },
  {
    type: 'image_load',
    label: 'Image Load',
    labelKo: '이미지 로드',
    category: 'context',
    tags: ['context', 'data'],
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { images: [], label: '이미지 로드' },
  },
  {
    type: 'document_load',
    label: 'Document Load',
    labelKo: '문서 로드',
    category: 'context',
    tags: ['context', 'data'],
    color: NODE_CATEGORY_COLORS.context,
    inputs: [],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { documents: [], label: '문서 로드' },
  },
  {
    type: 'plot_context',
    label: 'Plot',
    labelKo: '플롯',
    category: 'plot',
    tags: ['context', 'plot'],
    color: NODE_CATEGORY_COLORS.plot,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Data', type: 'source', position: 'right' }],
    defaultData: { selectedGenre: null, selectedStructure: null, wikiEntryId: null, label: '플롯' },
  },

  // ── Direction Nodes ──
  {
    type: 'pov',
    label: 'POV Control',
    labelKo: '시점 제어',
    category: 'direction',
    tags: ['direction'],
    color: NODE_CATEGORY_COLORS.direction,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { povType: 'third_limited', characterId: null, label: 'POV' },
  },
  {
    type: 'pacing',
    label: 'Pacing',
    labelKo: '텐션/호흡',
    category: 'direction',
    tags: ['direction'],
    color: NODE_CATEGORY_COLORS.direction,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { tension: 5, speed: 'normal', label: 'Pacing' },
  },
  {
    type: 'style_transfer',
    label: 'Style Transfer',
    labelKo: '문체 학습',
    category: 'direction',
    tags: ['direction', 'ai'],
    color: NODE_CATEGORY_COLORS.direction,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { sampleText: '', authorName: '', label: 'Style' },
  },

  // ── Processing Nodes ──
  {
    type: 'storyteller',
    label: 'AI Storyteller',
    labelKo: 'AI 스토리텔러',
    category: 'processing',
    tags: ['processing', 'ai'],
    color: NODE_CATEGORY_COLORS.processing,
    inputs: [
      { id: 'context', label: 'Context', type: 'target', position: 'left' },
      { id: 'direction', label: 'Direction', type: 'target', position: 'left' },
    ],
    outputs: [{ id: 'out', label: 'Text', type: 'source', position: 'right' }],
    defaultData: { prompt: '', label: 'Storyteller', provider: null },
  },
  {
    type: 'summarizer',
    label: 'Summarizer',
    labelKo: '스토리 축약',
    category: 'processing',
    tags: ['processing', 'ai'],
    color: NODE_CATEGORY_COLORS.processing,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Summary', type: 'source', position: 'right' }],
    defaultData: { maxTokens: 500, label: 'Summarizer' },
  },

  // ── Preview / Analysis Nodes ──
  {
    type: 'preview_changed',
    label: 'Preview Changed',
    labelKo: '변화 미리보기',
    category: 'special',
    tags: ['special', 'ai', 'character'],
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'character_in', label: '캐릭터', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Preview', type: 'source', position: 'right' }],
    defaultData: { label: '변화 미리보기' },
  },

  // ── Special Nodes ──
  {
    type: 'what_if',
    label: 'What-If Branch',
    labelKo: '평행우주 분기',
    category: 'special',
    tags: ['special', 'ai'],
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'in', label: 'Scene', type: 'target', position: 'left' }],
    outputs: [
      { id: 'branch_a', label: 'Branch A', type: 'source', position: 'right' },
      { id: 'branch_b', label: 'Branch B', type: 'source', position: 'right' },
    ],
    defaultData: { label: 'What-If' },
  },
  {
    type: 'show_dont_tell',
    label: "Show Don't Tell",
    labelKo: '묘사 증폭',
    category: 'special',
    tags: ['special', 'ai'],
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'in', label: 'Input', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { label: 'Show' },
  },
  {
    type: 'tikitaka',
    label: 'Tikitaka Dialogue',
    labelKo: '티키타카 대화',
    category: 'special',
    tags: ['special', 'ai', 'character'],
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'characters', label: 'Characters', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Dialogue', type: 'source', position: 'right' }],
    defaultData: { turns: 10, label: 'Tikitaka' },
  },
  {
    type: 'cliffhanger',
    label: 'Cliffhanger',
    labelKo: '절단신공',
    category: 'special',
    tags: ['special', 'ai'],
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'in', label: 'Scene', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Endings', type: 'source', position: 'right' }],
    defaultData: { count: 3, label: 'Cliffhanger' },
  },
  {
    type: 'virtual_reader',
    label: 'Virtual Reader',
    labelKo: '가상 독자',
    category: 'special',
    tags: ['special', 'ai'],
    color: NODE_CATEGORY_COLORS.special,
    inputs: [{ id: 'in', label: 'Manuscript', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Feedback', type: 'source', position: 'right' }],
    defaultData: { personas: ['사이다패스', '설정덕후', '감성독자'], label: 'Reader' },
  },

  // ── Detector Nodes ──
  {
    type: 'emotion_tracker',
    label: 'Emotion Tracker',
    labelKo: '감정 트래커',
    category: 'detector',
    tags: ['detector', 'ai'],
    color: NODE_CATEGORY_COLORS.detector,
    inputs: [{ id: 'in', label: 'Text', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Emotions', type: 'source', position: 'right' }],
    defaultData: { label: 'Emotion' },
  },
  {
    type: 'foreshadow_detector',
    label: 'Foreshadow Detector',
    labelKo: '복선 디텍터',
    category: 'detector',
    tags: ['detector', 'ai'],
    color: NODE_CATEGORY_COLORS.detector,
    inputs: [{ id: 'in', label: 'Text', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Foreshadows', type: 'source', position: 'right' }],
    defaultData: { label: 'Foreshadow' },
  },
  {
    type: 'conflict_defense',
    label: 'Conflict Defense',
    labelKo: '설정 충돌 방어',
    category: 'detector',
    tags: ['detector', 'ai'],
    color: NODE_CATEGORY_COLORS.detector,
    inputs: [{ id: 'in', label: 'Text', type: 'target', position: 'left' }],
    outputs: [{ id: 'out', label: 'Warnings', type: 'source', position: 'right' }],
    defaultData: { label: 'Conflict' },
  },

  // ── Output Nodes ──
  {
    type: 'save_content',
    label: 'Save Content',
    labelKo: '콘텐츠 저장',
    category: 'output',
    tags: ['output'],
    color: NODE_CATEGORY_COLORS.output,
    inputs: [{ id: 'content', label: 'Content', type: 'target', position: 'left' }],
    outputs: [],
    defaultData: { filename: 'content.md', label: 'Save Content' },
  },
  {
    type: 'preview_content',
    label: 'Preview Content',
    labelKo: '콘텐츠 미리보기',
    category: 'output',
    tags: ['output'],
    color: NODE_CATEGORY_COLORS.output,
    inputs: [{ id: 'content', label: 'Content', type: 'target', position: 'left' }],
    outputs: [],
    defaultData: { label: 'Preview Content' },
  },

  // ── Switch Node ──
  {
    type: 'switch',
    label: 'Switch',
    labelKo: '스위치',
    category: 'processing',
    tags: ['processing'],
    color: NODE_CATEGORY_COLORS.processing,
    inputs: [
      { id: 'in_1', label: '① 입력', type: 'target', position: 'left' },
      { id: 'in_2', label: '② 입력', type: 'target', position: 'left' },
      { id: 'in_3', label: '③ 입력', type: 'target', position: 'left' },
      { id: 'in_4', label: '④ 입력', type: 'target', position: 'left' },
      { id: 'in_5', label: '⑤ 입력', type: 'target', position: 'left' },
    ],
    outputs: [{ id: 'out', label: 'Output', type: 'source', position: 'right' }],
    defaultData: { selectedInput: 1, label: '스위치' },
  },

  // ── Structure Nodes ──
  {
    type: 'group',
    label: 'Group',
    labelKo: '그룹',
    category: 'structure',
    tags: ['structure'],
    color: NODE_CATEGORY_COLORS.structure,
    inputs: [],
    outputs: [],
    defaultData: { label: 'Group' },
  },

]
